/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NewMessageRouteImport } from './routes/new-message'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as RecoverIndexRouteImport } from './routes/recover.index'
import { Route as RecoverCodeRouteImport } from './routes/recover.code'
import { Route as RecoverPasswordRouteImport } from './routes/recover.password'
import { Route as SignupIndexRouteImport } from './routes/signup.index'
import { Route as SignupBirthdayRouteImport } from './routes/signup.birthday'
import { Route as SignupCheckEmailRouteImport } from './routes/signup.check-email'
import { Route as SignupGenderRouteImport } from './routes/signup.gender'
import { Route as SignupNameRouteImport } from './routes/signup.name'
import { Route as SignupPeopleRouteImport } from './routes/signup.people'
import { Route as SignupPhotoRouteImport } from './routes/signup.photo'
import { Route as SignupProfileRouteImport } from './routes/signup.profile'
import { Route as SignupUsernameRouteImport } from './routes/signup.username'
import { Route as UUsernameRouteImport } from './routes/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NewMessageRoute = NewMessageRouteImport.update({
  id: '/new-message',
  path: '/new-message',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverIndexRoute = RecoverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecoverRoute,
} as any)
const RecoverCodeRoute = RecoverCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => RecoverRoute,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => RecoverRoute,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignupRoute,
} as any)
const SignupBirthdayRoute = SignupBirthdayRouteImport.update({
  id: '/birthday',
  path: '/birthday',
  getParentRoute: () => SignupRoute,
} as any)
const SignupCheckEmailRoute = SignupCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => SignupRoute,
} as any)
const SignupGenderRoute = SignupGenderRouteImport.update({
  id: '/gender',
  path: '/gender',
  getParentRoute: () => SignupRoute,
} as any)
const SignupNameRoute = SignupNameRouteImport.update({
  id: '/name',
  path: '/name',
  getParentRoute: () => SignupRoute,
} as any)
const SignupPeopleRoute = SignupPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => SignupRoute,
} as any)
const SignupPhotoRoute = SignupPhotoRouteImport.update({
  id: '/photo',
  path: '/photo',
  getParentRoute: () => SignupRoute,
} as any)
const SignupProfileRoute = SignupProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SignupRoute,
} as any)
const SignupUsernameRoute = SignupUsernameRouteImport.update({
  id: '/username',
  path: '/username',
  getParentRoute: () => SignupRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clips': typeof ClipsRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRoute
  '/new-message': typeof NewMessageRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/recover': typeof RecoverRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/chat/$id': typeof ChatIdRoute
  '/recover/code': typeof RecoverCodeRoute
  '/recover/password': typeof RecoverPasswordRoute
  '/signup/birthday': typeof SignupBirthdayRoute
  '/signup/check-email': typeof SignupCheckEmailRoute
  '/signup/gender': typeof SignupGenderRoute
  '/signup/name': typeof SignupNameRoute
  '/signup/people': typeof SignupPeopleRoute
  '/signup/photo': typeof SignupPhotoRoute
  '/signup/profile': typeof SignupProfileRoute
  '/signup/username': typeof SignupUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/recover/': typeof RecoverIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clips': typeof ClipsRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRoute
  '/new-message': typeof NewMessageRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/welcome': typeof WelcomeRoute
  '/chat/$id': typeof ChatIdRoute
  '/recover/code': typeof RecoverCodeRoute
  '/recover/password': typeof RecoverPasswordRoute
  '/signup/birthday': typeof SignupBirthdayRoute
  '/signup/check-email': typeof SignupCheckEmailRoute
  '/signup/gender': typeof SignupGenderRoute
  '/signup/name': typeof SignupNameRoute
  '/signup/people': typeof SignupPeopleRoute
  '/signup/photo': typeof SignupPhotoRoute
  '/signup/profile': typeof SignupProfileRoute
  '/signup/username': typeof SignupUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/recover': typeof RecoverIndexRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clips': typeof ClipsRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRoute
  '/new-message': typeof NewMessageRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/recover': typeof RecoverRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/chat/$id': typeof ChatIdRoute
  '/recover/code': typeof RecoverCodeRoute
  '/recover/password': typeof RecoverPasswordRoute
  '/signup/birthday': typeof SignupBirthdayRoute
  '/signup/check-email': typeof SignupCheckEmailRoute
  '/signup/gender': typeof SignupGenderRoute
  '/signup/name': typeof SignupNameRoute
  '/signup/people': typeof SignupPeopleRoute
  '/signup/photo': typeof SignupPhotoRoute
  '/signup/profile': typeof SignupProfileRoute
  '/signup/username': typeof SignupUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/recover/': typeof RecoverIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clips'
    | '/create'
    | '/discover'
    | '/messages'
    | '/new-message'
    | '/notifications'
    | '/profile'
    | '/recover'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/welcome'
    | '/chat/$id'
    | '/recover/code'
    | '/recover/password'
    | '/signup/birthday'
    | '/signup/check-email'
    | '/signup/gender'
    | '/signup/name'
    | '/signup/people'
    | '/signup/photo'
    | '/signup/profile'
    | '/signup/username'
    | '/u/$username'
    | '/recover/'
    | '/signup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clips'
    | '/create'
    | '/discover'
    | '/messages'
    | '/new-message'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/signin'
    | '/welcome'
    | '/chat/$id'
    | '/recover/code'
    | '/recover/password'
    | '/signup/birthday'
    | '/signup/check-email'
    | '/signup/gender'
    | '/signup/name'
    | '/signup/people'
    | '/signup/photo'
    | '/signup/profile'
    | '/signup/username'
    | '/u/$username'
    | '/recover'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/clips'
    | '/create'
    | '/discover'
    | '/messages'
    | '/new-message'
    | '/notifications'
    | '/profile'
    | '/recover'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/welcome'
    | '/chat/$id'
    | '/recover/code'
    | '/recover/password'
    | '/signup/birthday'
    | '/signup/check-email'
    | '/signup/gender'
    | '/signup/name'
    | '/signup/people'
    | '/signup/photo'
    | '/signup/profile'
    | '/signup/username'
    | '/u/$username'
    | '/recover/'
    | '/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClipsRoute: typeof ClipsRoute
  CreateRoute: typeof CreateRoute
  DiscoverRoute: typeof DiscoverRoute
  MessagesRoute: typeof MessagesRoute
  NewMessageRoute: typeof NewMessageRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RecoverRoute: typeof RecoverRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  ChatIdRoute: typeof ChatIdRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-message': {
      id: '/new-message'
      path: '/new-message'
      fullPath: '/new-message'
      preLoaderRoute: typeof NewMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover/': {
      id: '/recover/'
      path: '/'
      fullPath: '/recover/'
      preLoaderRoute: typeof RecoverIndexRouteImport
      parentRoute: typeof RecoverRoute
    }
    '/recover/code': {
      id: '/recover/code'
      path: '/code'
      fullPath: '/recover/code'
      preLoaderRoute: typeof RecoverCodeRouteImport
      parentRoute: typeof RecoverRoute
    }
    '/recover/password': {
      id: '/recover/password'
      path: '/password'
      fullPath: '/recover/password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof RecoverRoute
    }
    '/signup/': {
      id: '/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/birthday': {
      id: '/signup/birthday'
      path: '/birthday'
      fullPath: '/signup/birthday'
      preLoaderRoute: typeof SignupBirthdayRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/check-email': {
      id: '/signup/check-email'
      path: '/check-email'
      fullPath: '/signup/check-email'
      preLoaderRoute: typeof SignupCheckEmailRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/gender': {
      id: '/signup/gender'
      path: '/gender'
      fullPath: '/signup/gender'
      preLoaderRoute: typeof SignupGenderRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/name': {
      id: '/signup/name'
      path: '/name'
      fullPath: '/signup/name'
      preLoaderRoute: typeof SignupNameRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/people': {
      id: '/signup/people'
      path: '/people'
      fullPath: '/signup/people'
      preLoaderRoute: typeof SignupPeopleRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/photo': {
      id: '/signup/photo'
      path: '/photo'
      fullPath: '/signup/photo'
      preLoaderRoute: typeof SignupPhotoRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/profile': {
      id: '/signup/profile'
      path: '/profile'
      fullPath: '/signup/profile'
      preLoaderRoute: typeof SignupProfileRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/username': {
      id: '/signup/username'
      path: '/username'
      fullPath: '/signup/username'
      preLoaderRoute: typeof SignupUsernameRouteImport
      parentRoute: typeof SignupRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RecoverRouteChildren {
  RecoverCodeRoute: typeof RecoverCodeRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  RecoverIndexRoute: typeof RecoverIndexRoute
}

const RecoverRouteChildren: RecoverRouteChildren = {
  RecoverCodeRoute: RecoverCodeRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  RecoverIndexRoute: RecoverIndexRoute,
}

const RecoverRouteWithChildren =
  RecoverRoute._addFileChildren(RecoverRouteChildren)

interface SignupRouteChildren {
  SignupBirthdayRoute: typeof SignupBirthdayRoute
  SignupCheckEmailRoute: typeof SignupCheckEmailRoute
  SignupGenderRoute: typeof SignupGenderRoute
  SignupNameRoute: typeof SignupNameRoute
  SignupPeopleRoute: typeof SignupPeopleRoute
  SignupPhotoRoute: typeof SignupPhotoRoute
  SignupProfileRoute: typeof SignupProfileRoute
  SignupUsernameRoute: typeof SignupUsernameRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupBirthdayRoute: SignupBirthdayRoute,
  SignupCheckEmailRoute: SignupCheckEmailRoute,
  SignupGenderRoute: SignupGenderRoute,
  SignupNameRoute: SignupNameRoute,
  SignupPeopleRoute: SignupPeopleRoute,
  SignupPhotoRoute: SignupPhotoRoute,
  SignupProfileRoute: SignupProfileRoute,
  SignupUsernameRoute: SignupUsernameRoute,
  SignupIndexRoute: SignupIndexRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClipsRoute: ClipsRoute,
  CreateRoute: CreateRoute,
  DiscoverRoute: DiscoverRoute,
  MessagesRoute: MessagesRoute,
  NewMessageRoute: NewMessageRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RecoverRoute: RecoverRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  ChatIdRoute: ChatIdRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
